# Generated by Django 2.1rc1 on 2018-07-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='brfbio',
            new_name='brief_bio',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='displayname',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
