# Generated by Django 2.1 on 2018-08-05 01:38

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('speech_date', models.DateField()),
                ('speech_text', models.TextField()),
                ('search_speech_text', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'ordering': ['speech_date'],
            },
        ),
    ]
