# Generated by Django 2.1 on 2018-08-05 02:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotu', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='speech',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_speech_text'], name='sotu_speech_search__e67881_gin'),
        ),
    ]
